app/bing/__init__.py
from flask import Blueprint

bp = Blueprint('bing', __name__, template_folder="templates/bing")

from app.bing import views

app/bing/views.py
from flask import render_template, request
from datetime import date
from app import cache
from app.bing import bp


@bp.route('/')
def index():
    from app.models import Bing
    bings = Bing.query.order_by(Bing.pub_date.desc())

    first = bings.first()
    if first is None or first.pub_date.date() < date.today():
        from app.utils import bing_spider
        bing_spider.spider()

    bings = Bing.query.order_by(Bing.pub_date.desc())
    page = request.args.get('page', 1, type=int)
    others = bings.paginate(page, 10, False)

    return render_template('bing/index.html', others=others, title='Bing')


@bp.route('/detail/<hsh>', methods=['GET', 'POST'])
def detail(hsh):
    first = cache.get(hsh)
    if first is None:
        from app.models import Bing
        first = Bing.query.filter_by(hsh=hsh).first()
        cache.set(str(hsh), first, timeout=5*60)
    return render_template('bing/detail.html', first=first, title='Bing')

app/templates/bing/detail.html
{% extends 'base.html' %} {% block content %}

<div class="container wow fadeIn">
{% if first %}
    <div class="row pt-4">
            <div class="jumbotron text-center">
                <h4 class="card-title font-bold pb-2"><strong>{{ first.pub_date.strftime('%Y-%m-%d') }}</strong></h4>
                <div class="view overlay my-4">
                    <img id="img" src="{{ first.url }}" class="img-fluid" alt="">
                    <a>
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>
                <h5 class="indigo-text font-bold mb-4">Photography</h5>
                <figcaption class="figure-caption text-center mb-4">@{{ first.copyright }}</figcaption>
                <p class="card-text text-left">
                    @{{ first.description }}
                </p>
                <a class="btn btn-outline-info btn-rounded waves-effect" onclick="download_image(this);">
                    <i class="fa fa-download pr-2" aria-hidden="true"></i> Download
                </a>
            </div>
    </div>
{% endif %}
</div>

{% endblock %} {% block scripts %}

<script>
    function download_image(btn) {
        var a = document.getElementById("img");
        var src = a.getAttribute("src");

        var x = new XMLHttpRequest();
        x.open("GET", src, true);
        x.responseType = 'blob';
        x.onload = function(e) {
            var url = window.URL.createObjectURL(x.response)
            var a = document.createElement('a');
            a.href = url
            a.download = ''
            a.click()
        }
        x.send();
        return true;
    }
</script>

{% endblock %}

app/templates/bing/index.html
{% extends 'base.html' %} {% block content %} {% if others %}

<div class="container wow fadeIn">
    <div class="row pt-4">
        <div class="col-md-7 mb-4">
            <div class="view overlay z-depth-1-half">
                <img id="img" src="{{ others.items[0].url }}" class="card-img-top" alt="">
                <div class="mask rgba-white-light"></div>
            </div>
        </div>

        <div class="col-md-5 mb-4">
            <h2>{{ others.items[0].pub_date.strftime('%Y-%m-%d') }}</h2>
            <hr>
            <p>
                @{{ others.items[0].copyright }}
            </p>
            <a class="btn btn-indigo btn-md" onclick="download_image(this);">
                Download
                <i class="fa fa-download ml-1"></i>
            </a>
            <a class="btn btn-indigo btn-md" href="{{ url_for('bing.detail',hsh=others.items[0].hsh) }}">
                Live Show
                <i class="fa fa-image ml-1"></i>
            </a>
        </div>
    </div>
    <div class="row">

        {% for item in others.items[1:] %}
        <div class="col-lg-4 col-md-12 mb-4">
            <div class="card">
                <div class="view overlay zoom">
                    <img src="{{ item.url }}" class="card-img-top" alt="">
                    <a>
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <a class="btn btn-indigo btn-md" href="{{ url_for('bing.detail',hsh=item.hsh) }}">
                            Live Show
                            <i class="fa fa-image ml-1"></i>
                        </a>
                        <small class="text-muted">{{ item.pub_date.strftime('%Y-%m-%d') }}</small>
                    </div>
                </div>
            </div>
        </div> {% endfor %}

    </div>

    <hr class="mb-5">

    <nav aria-label="Page navigation example" class="m-4">
        <ul class="pagination pg-blue justify-content-center">
            <li class="page-item {% if not others.has_prev %}disabled{% endif %}">
                <a class="page-link" href="{{ url_for('bing.index',page=others.prev_num) }}">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>

            {% for page in others.iter_pages(1,1,3,2) %} {% if page %}
            <li class="page-item {%if page==others.page%}active{%endif%}">
                <a class="page-link" href="{{ url_for('bing.index',page=page) }}">{{page}}</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">&hellip;</a>
            </li>
            {% endif %} {% endfor %}

            <li class="page-item {% if not others.has_next %}disabled{% endif %}">
                <a class="page-link" href="{{ url_for('bing.index',page=others.next_num) }}">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </nav>

</div>

{% endif %} {% endblock %} {% block scripts %}

<script>
    function download_image(btn) {
        var a = document.getElementById("img");
        var src = a.getAttribute("src");

        var x = new XMLHttpRequest();
        x.open("GET", src, true);
        x.responseType = 'blob';
        x.onload = function(e) {
            var url = window.URL.createObjectURL(x.response)
            var a = document.createElement('a');
            a.href = url
            a.download = ''
            a.click()
        }
        x.send();
        return true;
    }
</script>

{% endblock %}